package com.kaustubh.moviereviews.portal.models;

import com.kaustubh.moviereviews.portal.enums.Country;
import com.kaustubh.moviereviews.portal.enums.Gender;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;

@ApiModel(value = "Actor Model")
public class Actor {

    @ApiModelProperty(value = "Autogenerated Id of the actor")
    private String actorId;
    @ApiModelProperty(value = "Name of the actor", required = true)
    private String name;
    @ApiModelProperty(value = "Link of image of actor")
    private String image;
    @ApiModelProperty(value = "Date of Birth of actor. Format yyyy-MM-dd")
    private LocalDate dateOfBirth;
    @ApiModelProperty(value = "Country of actor", required = true)
    private Country country;
    @ApiModelProperty(value = "Gender of Actor", required = true)
    private Gender gender;
    @ApiModelProperty(value = "Initial value 0, auto updated by system")
    private int movieCount;

    public String getActorId() {
        return actorId;
    }

    public void setActorId(String actorId) {
        this.actorId = actorId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public int getMovieCount() {
        return movieCount;
    }

    public void setMovieCount(int movieCount) {
        this.movieCount = movieCount;
    }

    @Override
    public String toString() {
        return "Actor{" +
                "actorId='" + actorId + '\'' +
                ", name='" + name + '\'' +
                ", image='" + image + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", country=" + country +
                ", gender=" + gender +
                ", movieCount=" + movieCount +
                '}';
    }
}
